server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    resolver 127.0.0.11 valid=30s;

    location ~* ^/api/auth(/.*)?$ {
        set $upstream http://auth-service:8000/auth$1$is_args$args;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location ~* ^/api/links(/.*)?$ {
        set $upstream http://test-service:8000/links$1$is_args$args;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location ~* ^/api/questions(/.*)?$ {
        set $upstream http://test-service:8000/questions$1$is_args$args;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location ~* ^/api/tests(/.*)?$ {
        set $upstream http://test-service:8000/tests$1$is_args$args;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location ~* ^/api/attempts(/.*)?$ {
        set $upstream http://result-service:8000/attempts$1$is_args$args;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location ~* ^/api/analytics(/.*)?$ {
        set $upstream http://result-service:8000/analytics$1$is_args$args;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location ~* ^/api/rules(/.*)?$ {
        set $upstream http://reference-service:8000/rules$1$is_args$args;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
